### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by mugurcagdas** [ChatAnalyzer/ChatAnalyzer#28]
Dear Sir/Madam,

First of all i should say that i like your webapp. I'm computer engineer and graphic designer and if you confirm that i want to design logo for your webapp.
Kindly waiting your answer.

Best Regards,
Mugur Cagdas.

**Comment by mowolf** [comment]
Sure feel free to design a logo.

**Comment by cgdgsg22** [comment]
Hello,
Sorry for the late reply. I was working on another project.
I worked on 3 different designs. I hope you will like it. I will add more color variations too as soon as possible.
Which one do you prefer? (a,b,c)
If you have any other ideas, do not hesitate to communicate with me.

![variatons](https://user-images.githubusercontent.com/35704934/40288714-33c944ce-5cbd-11e8-97c5-134129ae3187.jpg)

**Comment by mugurcagdas** [comment]
Hello @mowolf 
Actually in the B design, i realize magnify glass=chat bubble and I indicated this idea with these three points. For me, its more professional with this way but i understand what you mention about chat bubble and edit B design; 
I hope you were mentioned this style. If so please specify which one you like. (We can edit color variations.)
![ugurumq2](https://user-images.githubusercontent.com/35704934/40329127-40faf950-5d51-11e8-9315-e9e524963b79.jpg)

**Comment by mowolf** [comment]
@mugurcagdas Great work! I like the ones in the first and last row best! 

In my opinion the yellow would be a good addition to the colors that I used in the project.
The colors:
[#2C3E50](https://www.google.es/search?q=%232C3E50&oq=%232C3E50)
[#18BC9C](https://www.google.es/search?ei=e-EDW9n6GMiZsAG_gZnIBQ&q=%2318BC9C&oq=%2318BC9C)
[#1a252f](https://www.google.es/search?ei=5-EDW7m3JcGXsAGJ-bfACg&q=%231a252f)

**Logo1:** I really like this one and I think you should create the image files and push it to the repo to keep your credit.

<img width="85" alt="bildschirmfoto 2018-05-22 um 11 27 07" src="https://user-images.githubusercontent.com/32100482/40354019-2ff67dd4-5db3-11e8-9ac3-e9d65736b830.png">

**Logo2:** What do you think of making the greyish background to [#2C3E50](https://www.google.es/search?q=%232C3E50&oq=%232C3E50)?
<img width="90" alt="bildschirmfoto 2018-05-22 um 11 21 34" src="https://user-images.githubusercontent.com/32100482/40353657-4caaf51e-5db2-11e8-8d9a-7f1de429b3eb.png">

These two logos would be perfect. 


**What we need:**

.ico file with x16,x32 and x64 pixel (for the browser icon, logo1)
.png files of different resolutions (logo1 & logo2)

Thanks a lot! @mugurcagdas once you pushed the files to the repo I will implement them!

**Comment by mugurcagdas** [comment]
Hello @mowolf 
Thanks for your reply.
I think it's compatible with project colors.
#2C3E50
#18BC9C
#1a252f

> Logo2: What do you think of making the greyish background to #2C3E50?
Actually It's your choice.
![pesieve](https://user-images.githubusercontent.com/35704934/40367085-3e4dbf22-5de1-11e8-916f-44f9d142d15a.JPG)

After these steps, i will send you .ico, .png and vector files with the sizes which you mention. And I will also create copyright credit and send you Pull Request to the main repo.

Btw, did you like the background with #2C3E50? Which one do you prefer?

I will create logo file and put the logos to there with my copyright credit. + I will use one of logos in Readme file. Which one you want to see top of readme file?
Thanks in advance.

**Comment by mowolf** [comment]
I think the one with the dark background is better. :) 

Jep perfect!

**Comment by mowolf** [comment]
Thanks @mugurcagdas ! Will implement the logos in the near future!
