### ISSUE TITLE
Selection of Most Used Words

### ISSUE THREAD

**Issue by mowolf** [ChatAnalyzer/ChatAnalyzer#6]
**Improvements:**
- divide the frequency of person A's use of the word by person B's, and sort by that ratio. That way you get words that person A is most likely to use compared to person B, and vice versa. 

- remove stopwords from the data. 
https://github.com/stopwords-iso/stopwords-iso

- exclude prepositions and really do a search on just nouns and verbs. 

Any ideas are welcome!

**Comment by ryanb93** [comment]
Maybe a toggle for showing stopwords or not.

**Comment by mowolf** [comment]
A textfield where you can search for a word and it shows you how often this word was used in the chat and by whom.

**Comment by mowolf** [comment]
> Maybe a toggle for showing stopwords or not.

@ryanb93 you can now filter out stopwords. Next thing is a a textfield where you can search for a word and it shows you how often this word was used in the chat and by whom.

**Comment by mowolf** [comment]
Close this for now as the main feautre is implemented. Will create a wiki to keep track of all the individual ideas.
